apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../crd/full
- ../../crd/full/llmisvc

patches:
- target:
    kind: CustomResourceDefinition
    annotationSelector: cert-manager.io/inject-ca-from
  path: patches/openshift-ca-patch.yaml
