/*
Copyright 2019 kubeflow.org.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/kubeflow/kfserving/pkg/apis/serving/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRouters implements RouterInterface
type FakeRouters struct {
	Fake *FakeServingV1alpha3
	ns   string
}

var routersResource = schema.GroupVersionResource{Group: "serving", Version: "v1alpha3", Resource: "routers"}

var routersKind = schema.GroupVersionKind{Group: "serving", Version: "v1alpha3", Kind: "Router"}

// Get takes name of the router, and returns the corresponding router object, and an error if there is any.
func (c *FakeRouters) Get(name string, options v1.GetOptions) (result *v1alpha3.Router, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(routersResource, c.ns, name), &v1alpha3.Router{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.Router), err
}

// List takes label and field selectors, and returns the list of Routers that match those selectors.
func (c *FakeRouters) List(opts v1.ListOptions) (result *v1alpha3.RouterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(routersResource, routersKind, c.ns, opts), &v1alpha3.RouterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha3.RouterList{ListMeta: obj.(*v1alpha3.RouterList).ListMeta}
	for _, item := range obj.(*v1alpha3.RouterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested routers.
func (c *FakeRouters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(routersResource, c.ns, opts))

}

// Create takes the representation of a router and creates it.  Returns the server's representation of the router, and an error, if there is any.
func (c *FakeRouters) Create(router *v1alpha3.Router) (result *v1alpha3.Router, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(routersResource, c.ns, router), &v1alpha3.Router{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.Router), err
}

// Update takes the representation of a router and updates it. Returns the server's representation of the router, and an error, if there is any.
func (c *FakeRouters) Update(router *v1alpha3.Router) (result *v1alpha3.Router, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(routersResource, c.ns, router), &v1alpha3.Router{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.Router), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRouters) UpdateStatus(router *v1alpha3.Router) (*v1alpha3.Router, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(routersResource, "status", c.ns, router), &v1alpha3.Router{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.Router), err
}

// Delete takes name of the router and deletes it. Returns an error if one occurs.
func (c *FakeRouters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(routersResource, c.ns, name), &v1alpha3.Router{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRouters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(routersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha3.RouterList{})
	return err
}

// Patch applies the patch and returns the patched router.
func (c *FakeRouters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.Router, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(routersResource, c.ns, name, pt, data, subresources...), &v1alpha3.Router{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.Router), err
}
