apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kserve

resources:
- ../../../crd/full/clusterstoragecontainer
- ../../../base

components:
- ../../../components/llmisvc


