kserve:
  version: v0.18.0
  localmodel:
    enabled: false
    controller:
      image: kserve/kserve-localmodel-controller
      tag: ''
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 200Mi
    jobNamespace: kserve-localmodel-jobs
    jobTTLSecondsAfterFinished: 3600
    defaultJobImage: kserve/storage-initializer
    defaultJobTag: ''
    securityContext:
      fsGroup: 1000
    disableVolumeManagement: false
    agent:
      nodeSelector: {}
      affinity: {}
      tolerations: []
      hostPath: /mnt/models
      image: kserve/kserve-localmodelnode-agent
      tag: ''
      reconcilationFrequencyInSecs: 60
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
  security:
    autoMountServiceAccountToken: true
  inferenceservice:
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
  opentelemetryCollector:
    scrapeInterval: 5s
    metricReceiverEndpoint: keda-otel-scaler.keda.svc:4317
    metricScalerEndpoint: keda-otel-scaler.keda.svc:4318
    resource:
      cpuLimit: '1'
      memoryLimit: 2Gi
      cpuRequest: 200m
      memoryRequest: 512Mi
  autoscaler:
    scaleUpStabilizationWindowSeconds: '0'
    scaleDownStabilizationWindowSeconds: '300'
  localmodelnode:
    controller:
      image: kserve/kserve-localmodelnode-agent
      tag: ''
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 200Mi
      nodeSelector:
        kserve/localmodel: worker
      affinity: {}
      tolerations: []
