#!/bin/bash
# Auto-generated from kserve-images.env - DO NOT EDIT MANUALLY

# E2E environment variables
DOCKER_IMAGES_PATH="${DOCKER_IMAGES_PATH:-/tmp/docker-images}"

# Image URL to use all building/pushing image targets
TAG="${TAG:-latest}"
CONTROLLER_IMG="${CONTROLLER_IMG:-kserve-controller}"
AGENT_IMG="${AGENT_IMG:-agent}"
ROUTER_IMG="${ROUTER_IMG:-router}"
SKLEARN_IMG="${SKLEARN_IMG:-sklearnserver}"
XGB_IMG="${XGB_IMG:-xgbserver}"
LGB_IMG="${LGB_IMG:-lgbserver}"
PREDICTIVE_IMG="${PREDICTIVE_IMG:-predictiveserver}"
PMML_IMG="${PMML_IMG:-pmmlserver}"
PADDLE_IMG="${PADDLE_IMG:-paddleserver}"
CUSTOM_MODEL_IMG="${CUSTOM_MODEL_IMG:-custom-model}"
CUSTOM_MODEL_GRPC_IMG="${CUSTOM_MODEL_GRPC_IMG:-custom-model-grpc}"
CUSTOM_MODEL_GRPC_IMG_TAG="${CUSTOM_MODEL_GRPC_IMG_TAG:-${KO_DOCKER_REPO}/${CUSTOM_MODEL_GRPC_IMG}:${TAG}}"
IMAGE_TRANSFORMER_IMG="${IMAGE_TRANSFORMER_IMG:-image-transformer}"
IMAGE_TRANSFORMER_IMG_TAG="${IMAGE_TRANSFORMER_IMG_TAG:-${KO_DOCKER_REPO}/${IMAGE_TRANSFORMER_IMG}:${TAG}}"
CUSTOM_TRANSFORMER_GRPC_IMG="${CUSTOM_TRANSFORMER_GRPC_IMG:-custom-image-transformer-grpc}"
HUGGINGFACE_IMG="${HUGGINGFACE_IMG:-huggingfaceserver}"
HUGGINGFACE_SERVER_CPU_IMG="${HUGGINGFACE_SERVER_CPU_IMG:-huggingfaceserver-cpu}"
AIF_IMG="${AIF_IMG:-aiffairness}"
ART_IMG="${ART_IMG:-art-explainer}"
STORAGE_INIT_IMG="${STORAGE_INIT_IMG:-storage-initializer}"
QPEXT_IMG="${QPEXT_IMG:-qpext}"
SUCCESS_200_ISVC_IMG="${SUCCESS_200_ISVC_IMG:-success-200-isvc}"
ERROR_404_ISVC_IMG="${ERROR_404_ISVC_IMG:-error-404-isvc}"
LLMISVC_CONTROLLER_IMG="${LLMISVC_CONTROLLER_IMG:-kserve-llmisvc-controller}"
LOCALMODEL_CONTROLLER_IMG="${LOCALMODEL_CONTROLLER_IMG:-kserve-localmodel-controller}"
LOCALMODEL_AGENT_IMG="${LOCALMODEL_AGENT_IMG:-kserve-localmodelnode-agent}"

# CI mode: export all variables to GITHUB_ENV
if [[ "${1:-}" == "--ci" ]]; then
  for var in DOCKER_IMAGES_PATH TAG CONTROLLER_IMG AGENT_IMG ROUTER_IMG SKLEARN_IMG XGB_IMG LGB_IMG PREDICTIVE_IMG PMML_IMG PADDLE_IMG CUSTOM_MODEL_IMG CUSTOM_MODEL_GRPC_IMG CUSTOM_MODEL_GRPC_IMG_TAG IMAGE_TRANSFORMER_IMG IMAGE_TRANSFORMER_IMG_TAG CUSTOM_TRANSFORMER_GRPC_IMG HUGGINGFACE_IMG HUGGINGFACE_SERVER_CPU_IMG AIF_IMG ART_IMG STORAGE_INIT_IMG QPEXT_IMG SUCCESS_200_ISVC_IMG ERROR_404_ISVC_IMG LLMISVC_CONTROLLER_IMG LOCALMODEL_CONTROLLER_IMG LOCALMODEL_AGENT_IMG; do
    echo "${var}=${!var}" >> $GITHUB_ENV
  done
  echo "✅ Exported KServe image variables to GITHUB_ENV"
fi
