apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kserve-kernelcachenode-agent
spec:
  template:
    spec:
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
