# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving
from kfserving.models.knative_volatile_time import KnativeVolatileTime  # noqa: E501
from kfserving.rest import ApiException


class TestKnativeVolatileTime(unittest.TestCase):
    """KnativeVolatileTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKnativeVolatileTime(self):
        """Test KnativeVolatileTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.models.knative_volatile_time.KnativeVolatileTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
