# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving
from kfserving.models.v1alpha1_status_configuration_spec import V1alpha1StatusConfigurationSpec  # noqa: E501
from kfserving.rest import ApiException


class TestV1alpha1StatusConfigurationSpec(unittest.TestCase):
    """V1alpha1StatusConfigurationSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1StatusConfigurationSpec(self):
        """Test V1alpha1StatusConfigurationSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.models.v1alpha1_status_configuration_spec.V1alpha1StatusConfigurationSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
