{{- if eq (include "kserve-common.optionalResourceEnabled" (dict
      "value" .Values.kserve.certManager.enabled
      "default" .Values.kserve.createSharedResources)) "true" }}
{{- include "kserve-common.renderSimpleResource" (dict
  "baseFile" "files/common/certmanager.yaml"
  "replaceNamespace" true
  "context" .) -}}
{{- end }}
