{{- if eq (include "kserve-common.featureEnabled" (dict "enabled" .Values.kserve.storagecontainer.enabled "fallback" .Values.kserve.createSharedResources)) "true" }}
{{- include "kserve-common.renderPatchedResource" (dict
  "baseFile" "files/common/storagecontainer.yaml"
  "patchFile" "files/common/storagecontainer-patch.yaml"
  "replaceNamespace" false
  "context" .) -}}
{{- end }}
