# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving.sdk
from kfserving.sdk.models.io_k8s_api_core_v1_limit_range import IoK8sApiCoreV1LimitRange  # noqa: E501
from kfserving.sdk.rest import ApiException


class TestIoK8sApiCoreV1LimitRange(unittest.TestCase):
    """IoK8sApiCoreV1LimitRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1LimitRange(self):
        """Test IoK8sApiCoreV1LimitRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.sdk.models.io_k8s_api_core_v1_limit_range.IoK8sApiCoreV1LimitRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
