# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving.sdk
from kfserving.sdk.models.io_k8s_apimachinery_pkg_apis_meta_v1_status import IoK8sApimachineryPkgApisMetaV1Status  # noqa: E501
from kfserving.sdk.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1Status(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1Status unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1Status(self):
        """Test IoK8sApimachineryPkgApisMetaV1Status"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.sdk.models.io_k8s_apimachinery_pkg_apis_meta_v1_status.IoK8sApimachineryPkgApisMetaV1Status()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
