# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving.sdk
from kfserving.sdk.models.com_github_knative_pkg_apis_volatile_time import ComGithubKnativePkgApisVolatileTime  # noqa: E501
from kfserving.sdk.rest import ApiException


class TestComGithubKnativePkgApisVolatileTime(unittest.TestCase):
    """ComGithubKnativePkgApisVolatileTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComGithubKnativePkgApisVolatileTime(self):
        """Test ComGithubKnativePkgApisVolatileTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.sdk.models.com_github_knative_pkg_apis_volatile_time.ComGithubKnativePkgApisVolatileTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
