# coding: utf-8

"""
    KFServing

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving.sdk
from kfserving.sdk.models.com_github_kubeflow_kfserving_pkg_apis_serving_v1alpha1_frameworks_config import ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig  # noqa: E501
from kfserving.sdk.rest import ApiException


class TestComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig(unittest.TestCase):
    """ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig(self):
        """Test ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.sdk.models.com_github_kubeflow_kfserving_pkg_apis_serving_v1alpha1_frameworks_config.ComGithubKubeflowKfservingPkgApisServingV1alpha1FrameworksConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
