# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving.sdk
from kfserving.sdk.models.kfserving_v1alpha1_kf_service_list import KfservingV1alpha1KFServiceList  # noqa: E501
from kfserving.sdk.rest import ApiException


class TestKfservingV1alpha1KFServiceList(unittest.TestCase):
    """KfservingV1alpha1KFServiceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKfservingV1alpha1KFServiceList(self):
        """Test KfservingV1alpha1KFServiceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.sdk.models.kfserving_v1alpha1_kf_service_list.KfservingV1alpha1KFServiceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
