# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfserving.sdk
from kfserving.sdk.models.io_k8s_apimachinery_pkg_apis_meta_v1_group_version_kind import IoK8sApimachineryPkgApisMetaV1GroupVersionKind  # noqa: E501
from kfserving.sdk.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1GroupVersionKind(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1GroupVersionKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1GroupVersionKind(self):
        """Test IoK8sApimachineryPkgApisMetaV1GroupVersionKind"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfserving.sdk.models.io_k8s_apimachinery_pkg_apis_meta_v1_group_version_kind.IoK8sApimachineryPkgApisMetaV1GroupVersionKind()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
