---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kernelcache.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: $(kserveNamespace)/kernelcache-serving-cert
webhooks:
  - name: kernelcache.kserve-webhook-server.defaulter
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kernelcache.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: $(kserveNamespace)/kernelcache-serving-cert
webhooks:
  - name: kernelcache.kserve-webhook-server.validator
