apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-localmodel-permfix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-localmodel-permfix-role
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["kserve-localmodel-permissions-scc"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kserve-localmodel-permfix-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-localmodel-permfix-role
subjects:
- kind: ServiceAccount
  name: kserve-localmodel-permfix
  namespace: opendatahub
