apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kserve-kernelcachenode-agent
  namespace: kserve
spec:
  template:
    spec:
      containers:
      - name: manager
        image: ${KO_DOCKER_REPO}/kserve-kernelcachenode-agent:${KSERVE_TAG}
