apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kserve-kernelcachenode-agent
  namespace: kserve
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your agent image URL
      - image: kserve/kserve-kernelcachenode-agent:latest
        name: manager
