apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kserve-kernelcache-nodegroup-agent-manager
  namespace: kserve
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  resourceNames:
  - kserve-kernelcachenode-agent
  verbs:
  - get
  - patch
