---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-kernelcache-nodegroup-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups:
  - apps
  resourceNames:
  - kserve-kernelcachenode-agent
  resources:
  - daemonsets
  verbs:
  - get
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - kernelcachenodegroups
  - kernelcaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - kernelcachenodes
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - kernelcaches/status
  verbs:
  - get
  - patch
  - update
