apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance:  kserve-kernelcache-controller-manager
    app.kubernetes.io/managed-by:  kserve-kernelcache-controller-manager
    app.kubernetes.io/name:  kserve-kernelcache-controller-manager
  name: kserve-kernelcache-controller-manager
