# coding: utf-8

"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from kfserving.sdk.models.io_k8s_api_core_v1_client_ip_config import IoK8sApiCoreV1ClientIPConfig  # noqa: F401,E501


class IoK8sApiCoreV1SessionAffinityConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_ip': 'IoK8sApiCoreV1ClientIPConfig'
    }

    attribute_map = {
        'client_ip': 'clientIP'
    }

    def __init__(self, client_ip=None):  # noqa: E501
        """IoK8sApiCoreV1SessionAffinityConfig - a model defined in Swagger"""  # noqa: E501

        self._client_ip = None
        self.discriminator = None

        if client_ip is not None:
            self.client_ip = client_ip

    @property
    def client_ip(self):
        """Gets the client_ip of this IoK8sApiCoreV1SessionAffinityConfig.  # noqa: E501

        clientIP contains the configurations of Client IP based session affinity.  # noqa: E501

        :return: The client_ip of this IoK8sApiCoreV1SessionAffinityConfig.  # noqa: E501
        :rtype: IoK8sApiCoreV1ClientIPConfig
        """
        return self._client_ip

    @client_ip.setter
    def client_ip(self, client_ip):
        """Sets the client_ip of this IoK8sApiCoreV1SessionAffinityConfig.

        clientIP contains the configurations of Client IP based session affinity.  # noqa: E501

        :param client_ip: The client_ip of this IoK8sApiCoreV1SessionAffinityConfig.  # noqa: E501
        :type: IoK8sApiCoreV1ClientIPConfig
        """

        self._client_ip = client_ip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiCoreV1SessionAffinityConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiCoreV1SessionAffinityConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
