apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kserve

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: kernelcache-webhook-key
  type: Opaque
  envs:
  - mutation.env  # MUTATION_SIGNING_KEY=<base64-random>
