---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-kernelcachenode-agent-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - kernelcachenodegroups
  - kernelcachenodes
  - kernelcaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - kernelcachenodes/status
  verbs:
  - get
  - patch
  - update
