apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance:  kserve-kernelcachenode-agent
    app.kubernetes.io/managed-by:  kserve-kernelcachenode-agent
    app.kubernetes.io/name:  kserve-kernelcachenode-agent
  name: kserve-kernelcachenode-agent
  namespace: kserve
