{{- if eq (include "kserve-common.featureEnabled" (dict "enabled" .Values.kserve.inferenceServiceConfig.enabled "fallback" .Values.kserve.createSharedResources)) "true" }}
{{- include "kserve-common.renderPatchedResource" (dict
  "baseFile" "files/common/configmap.yaml"
  "patchFile" "files/common/configmap-patch.yaml"
  "replaceNamespace" true
  "context" .) -}}
{{- end }}
