{{- $selfSignedCfg := include "kserve-llmisvc-crd.selfSignedCertsConfig" . | fromJson -}}
{{- if $selfSignedCfg.enabled }}
{{- $ca := include "kserve-llmisvc-crd.selfSignedCA" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $selfSignedCfg.caSecretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ $ca.Cert | b64enc }}
  tls.key: {{ $ca.Key | b64enc }}
{{- end }}
