/*
Copyright 2023 The KServe Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kserve/kserve/pkg/apis/serving/v1alpha1"
	scheme "github.com/kserve/kserve/pkg/clientv1alpha1/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TrainedModelListsGetter has a method to return a TrainedModelListInterface.
// A group's client should implement this interface.
type TrainedModelListsGetter interface {
	TrainedModelLists(namespace string) TrainedModelListInterface
}

// TrainedModelListInterface has methods to work with TrainedModelList resources.
type TrainedModelListInterface interface {
	Create(ctx context.Context, trainedModelList *v1alpha1.TrainedModelList, opts v1.CreateOptions) (*v1alpha1.TrainedModelList, error)
	Update(ctx context.Context, trainedModelList *v1alpha1.TrainedModelList, opts v1.UpdateOptions) (*v1alpha1.TrainedModelList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TrainedModelList, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TrainedModelListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrainedModelList, err error)
	TrainedModelListExpansion
}

// trainedModelLists implements TrainedModelListInterface
type trainedModelLists struct {
	client rest.Interface
	ns     string
}

// newTrainedModelLists returns a TrainedModelLists
func newTrainedModelLists(c *ServingV1alpha1Client, namespace string) *trainedModelLists {
	return &trainedModelLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trainedModelList, and returns the corresponding trainedModelList object, and an error if there is any.
func (c *trainedModelLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TrainedModelList, err error) {
	result = &v1alpha1.TrainedModelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trainedmodellists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TrainedModelLists that match those selectors.
func (c *trainedModelLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TrainedModelListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TrainedModelListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trainedmodellists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested trainedModelLists.
func (c *trainedModelLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("trainedmodellists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a trainedModelList and creates it.  Returns the server's representation of the trainedModelList, and an error, if there is any.
func (c *trainedModelLists) Create(ctx context.Context, trainedModelList *v1alpha1.TrainedModelList, opts v1.CreateOptions) (result *v1alpha1.TrainedModelList, err error) {
	result = &v1alpha1.TrainedModelList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("trainedmodellists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trainedModelList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a trainedModelList and updates it. Returns the server's representation of the trainedModelList, and an error, if there is any.
func (c *trainedModelLists) Update(ctx context.Context, trainedModelList *v1alpha1.TrainedModelList, opts v1.UpdateOptions) (result *v1alpha1.TrainedModelList, err error) {
	result = &v1alpha1.TrainedModelList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trainedmodellists").
		Name(trainedModelList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trainedModelList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the trainedModelList and deletes it. Returns an error if one occurs.
func (c *trainedModelLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trainedmodellists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *trainedModelLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trainedmodellists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched trainedModelList.
func (c *trainedModelLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrainedModelList, err error) {
	result = &v1alpha1.TrainedModelList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("trainedmodellists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
