{{- if .Values.kserve.llmisvcConfigs.enabled }}
{{- $content := .Files.Get "files/llmisvcconfigs/resources.yaml" -}}
{{ include "kserve-common.replaceNamespace" (list $content .Release.Namespace) }}
{{- end }}
