---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-llmisvc-distro-role
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - openshift-ai-llminferenceservice-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
