/*
Copyright 2026 The KServe Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package kernelcachenode

import (
	"context"
	"maps"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	"github.com/kserve/kserve/pkg/apis/serving/v1alpha1"
	"github.com/kserve/kserve/pkg/constants"
	kernelcacheconfig "github.com/kserve/kserve/pkg/kernelcache/config"
	kernelcachelabels "github.com/kserve/kserve/pkg/kernelcache/labels"
	"github.com/kserve/kserve/pkg/kernelcache/nodegroup"
)

// Controller setup and event filtering.
func (r *KernelCacheNodeReconciler) SetupWithManager(mgr ctrl.Manager) error {
	currentNodePredicate := r.currentNodePredicate()

	return ctrl.NewControllerManagedBy(mgr).
		For(&v1alpha1.KernelCacheNode{}, builder.WithPredicates(currentNodePredicate)).
		Watches(&v1alpha1.KernelCache{}, handler.EnqueueRequestsFromMapFunc(r.enqueueCurrentNode)).
		Watches(&corev1.Node{}, handler.EnqueueRequestsFromMapFunc(r.enqueueCurrentNode), builder.WithPredicates(r.currentNodeReadinessPredicate())).
		Watches(&corev1.Pod{}, handler.EnqueueRequestsFromMapFunc(r.enqueueCurrentNodeForPod), builder.WithPredicates(r.currentPodPredicate())).
		Watches(&batchv1.Job{}, handler.EnqueueRequestsFromMapFunc(r.enqueueCurrentNodeForJob), builder.WithPredicates(r.currentJobPredicate())).
		Watches(&corev1.ConfigMap{}, handler.EnqueueRequestsFromMapFunc(r.enqueueCurrentNodeForConfigMap), builder.WithPredicates(r.inferenceServiceConfigMapPredicate())).
		Complete(r)
}

// Ignore status-only updates generated by this controller.
func (r *KernelCacheNodeReconciler) currentNodePredicate() predicate.Predicate {
	return predicate.And(
		predicate.NewPredicateFuncs(func(obj client.Object) bool {
			return obj.GetName() == r.NodeName
		}),
		predicate.GenerationChangedPredicate{},
	)
}

func (r *KernelCacheNodeReconciler) currentNodeReadinessPredicate() predicate.Funcs {
	return predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool {
			node, ok := e.Object.(*corev1.Node)
			return ok && node.Name == r.NodeName
		},
		UpdateFunc: func(e event.UpdateEvent) bool {
			oldNode, oldOK := e.ObjectOld.(*corev1.Node)
			newNode, newOK := e.ObjectNew.(*corev1.Node)
			return oldOK && newOK && newNode.Name == r.NodeName &&
				(nodegroup.IsNodeReady(*oldNode) != nodegroup.IsNodeReady(*newNode) ||
					!maps.Equal(oldNode.Labels, newNode.Labels))
		},
		DeleteFunc: func(e event.DeleteEvent) bool {
			return false
		},
	}
}

func (r *KernelCacheNodeReconciler) enqueueCurrentNode(context.Context, client.Object) []reconcile.Request {
	return []reconcile.Request{{NamespacedName: types.NamespacedName{Name: r.NodeName}}}
}

func (r *KernelCacheNodeReconciler) currentJobPredicate() predicate.Funcs {
	return predicate.NewPredicateFuncs(r.isRelevantJob)
}

func (r *KernelCacheNodeReconciler) isRelevantJob(obj client.Object) bool {
	labels := obj.GetLabels()
	if labels[kernelCacheNameLabel] == "" || labels[kernelCacheNamespaceLabel] == "" {
		return false
	}
	if nodeName, ok := labels[kernelCacheNodeLabel]; !ok || nodeName != kernelcachelabels.Value(r.NodeName) {
		return false
	}
	return true
}

func (r *KernelCacheNodeReconciler) inferenceServiceConfigMapPredicate() predicate.Funcs {
	return predicate.NewPredicateFuncs(func(obj client.Object) bool {
		return obj.GetNamespace() == constants.KServeNamespace && obj.GetName() == constants.InferenceServiceConfigMapName
	})
}

func (r *KernelCacheNodeReconciler) enqueueCurrentNodeForJob(ctx context.Context, obj client.Object) []reconcile.Request {
	if !r.isRelevantJob(obj) {
		return nil
	}
	config, err := kernelcacheconfig.Load(ctx, r.Client)
	if err != nil {
		r.Log.Error(err, "unable to load KernelCache configuration for Job event", "job", client.ObjectKeyFromObject(obj))
		return nil
	}
	if obj.GetNamespace() != config.JobNamespace {
		return nil
	}
	return r.enqueueCurrentNode(ctx, obj)
}

func (r *KernelCacheNodeReconciler) enqueueCurrentNodeForConfigMap(ctx context.Context, obj client.Object) []reconcile.Request {
	return r.enqueueCurrentNode(ctx, obj)
}

func (r *KernelCacheNodeReconciler) currentPodPredicate() predicate.Funcs {
	return predicate.NewPredicateFuncs(func(obj client.Object) bool {
		return obj.GetLabels()[constants.InferenceServicePodLabelKey] != ""
	})
}

func (r *KernelCacheNodeReconciler) enqueueCurrentNodeForPod(_ context.Context, obj client.Object) []reconcile.Request {
	if obj.GetLabels()[constants.InferenceServicePodLabelKey] == "" {
		return nil
	}

	if obj.GetAnnotations()[constants.KernelCacheUsageAnnotationKey] != "" {
		pod, ok := obj.(*corev1.Pod)
		if !ok || pod.Spec.NodeName != r.NodeName {
			return nil
		}
		return []reconcile.Request{{NamespacedName: types.NamespacedName{Name: r.NodeName}}}
	}

	return nil
}
