apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kserve

labels:
- pairs:
    app.kubernetes.io/component: llm-monitoring
    app.kubernetes.io/part-of: kserve

resources:
- rbac.yaml
