apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-template-ibm-spyre-ppc64le
  annotations:
    openshift.io/display-name: vLLM IBM Spyre ppc64le LLMInferenceServiceConfig
    openshift.io/description: vLLM IBM Spyre ppc64le LLMInferenceServiceConfig for LLMInferenceService.
    opendatahub.io/recommended-accelerators: '["ibm.com/spyre_pf"]'
spec:
  template:
    containers:
      - name: main
        image: placeholder
        env:
          - name: HF_HOME
            value: /tmp/hf_home
          - name: FLEX_COMPUTE
            value: SENTIENT
          - name: FLEX_DEVICE
            value: PF
          - name: TOKENIZERS_PARALLELISM
            value: "false"
          - name: DTLOG_LEVEL
            value: error
          - name: TORCH_SENDNN_LOG
            value: CRITICAL
          - name: VLLM_SPYRE_USE_CB
            value: "1"
