apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-template-nvidia-cuda
  annotations:
    openshift.io/display-name: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig
    description: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig for LLMInferenceService.
spec:
  template:
    containers:
      - name: main
        image: placeholder
