apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: controller-namespace-rbac
    app.kubernetes.io/name: kserve
    app.kubernetes.io/part-of: llminferenceservice
  name: kserve-llmisvc-controller-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
