apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller-namespace-rbac
    app.kubernetes.io/name: kserve
    app.kubernetes.io/part-of: llminferenceservice
  name: kserve-llmisvc-controller-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kserve-llmisvc-controller-secrets
subjects:
- kind: ServiceAccount
  name: $(llmisvc-serviceAccountName)
  namespace: kserve
