apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- role.yaml
- clusterrolebinding.yaml
- controller_namespace_secrets_role.yaml
- controller_namespace_secrets_role_binding.yaml
- scheduler_auth_delegator_clusterrolebinding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- service_account.yaml
