/*
Copyright 2019 kubeflow.org.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha3

import (
	time "time"

	servingv1alpha3 "github.com/kubeflow/kfserving/pkg/apis/serving/v1alpha3"
	versioned "github.com/kubeflow/kfserving/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/kfserving/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha3 "github.com/kubeflow/kfserving/pkg/client/listers/serving/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RouterInformer provides access to a shared informer and lister for
// Routers.
type RouterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha3.RouterLister
}

type routerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRouterInformer constructs a new informer for Router type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRouterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRouterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRouterInformer constructs a new informer for Router type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRouterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ServingV1alpha3().Routers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ServingV1alpha3().Routers(namespace).Watch(options)
			},
		},
		&servingv1alpha3.Router{},
		resyncPeriod,
		indexers,
	)
}

func (f *routerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRouterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *routerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&servingv1alpha3.Router{}, f.defaultInformer)
}

func (f *routerInformer) Lister() v1alpha3.RouterLister {
	return v1alpha3.NewRouterLister(f.Informer().GetIndexer())
}
