# Copyright 2026 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kserve
from kserve.models.v1alpha1_kernel_cache_capture_status import V1alpha1KernelCacheCaptureStatus  # noqa: E501
from kserve.rest import ApiException

class TestV1alpha1KernelCacheCaptureStatus(unittest.TestCase):
    """V1alpha1KernelCacheCaptureStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1KernelCacheCaptureStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kserve.models.v1alpha1_kernel_cache_capture_status.V1alpha1KernelCacheCaptureStatus()  # noqa: E501
        if include_optional :
            return V1alpha1KernelCacheCaptureStatus(
                active_session = kserve.models.v1alpha1_kernel_cache_capture_session.V1alpha1KernelCacheCaptureSession(
                    id = '0', 
                    node_name = '0', 
                    pod_name = '0', 
                    requested_node_group = '0', ), 
                artifact = kserve.models.v1alpha1_kernel_cache_artifact.V1alpha1KernelCacheArtifact(
                    cache_paths = [
                        kserve.models.v1alpha1_kernel_cache_path.V1alpha1KernelCachePath(
                            container_name = '0', 
                            container_path = '0', 
                            oci_path = '0', )
                        ], 
                    identity = kserve.models.v1alpha1_kernel_cache_identity.V1alpha1KernelCacheIdentity(
                        factors = {
                            'key' : '0'
                            }, 
                        footprints = kserve.models.v1alpha1_kernel_cache_footprints.V1alpha1KernelCacheFootprints(
                            compatibility_footprint = '0', 
                            workload_footprint = '0', ), ), 
                    image_reference = '0', ), 
                captured_at = None, 
                captured_cache_size_bytes = 56, 
                conditions = [
                    None
                    ], 
                kernel_cache_ref = kserve.models.v1alpha1_namespaced_name.V1alpha1NamespacedName(
                    name = '0', 
                    namespace = '0', ), 
                phase = '0', 
                runtime_result = {
                    'key' : '0'
                    }, 
                signing = kserve.models.v1alpha1_kernel_cache_signing_status.V1alpha1KernelCacheSigningStatus(
                    message = '0', 
                    mode = '0', 
                    reason = '0', 
                    signed = True, 
                    signed_at = None, 
                    state = '0', )
            )
        else :
            return V1alpha1KernelCacheCaptureStatus(
        )

    def testV1alpha1KernelCacheCaptureStatus(self):
        """Test V1alpha1KernelCacheCaptureStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
