# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kserve
from kserve.models.v1beta1_canary_spec import V1beta1CanarySpec  # noqa: E501
from kserve.rest import ApiException

class TestV1beta1CanarySpec(unittest.TestCase):
    """V1beta1CanarySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1beta1CanarySpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kserve.models.v1beta1_canary_spec.V1beta1CanarySpec()  # noqa: E501
        if include_optional :
            return V1beta1CanarySpec(
                predictor = kserve.models.v1beta1_predictor_spec.V1beta1PredictorSpec(
                    active_deadline_seconds = 56, 
                    affinity = None, 
                    annotations = {
                        'key' : '0'
                        }, 
                    auto_scaling = kserve.models.v1beta1_auto_scaling_spec.V1beta1AutoScalingSpec(
                        behavior = None, 
                        metrics = [
                            kserve.models.v1beta1_metrics_spec.V1beta1MetricsSpec(
                                external = kserve.models.v1beta1_external_metric_source.V1beta1ExternalMetricSource(
                                    authentication_ref = kserve.models.v1beta1_ext_metric_authentication.V1beta1ExtMetricAuthentication(
                                        auth_modes = '0', 
                                        authentication_ref = kserve.models.v1beta1_authentication_ref.V1beta1AuthenticationRef(
                                            name = '0', ), ), 
                                    metric = kserve.models.v1beta1_external_metrics.V1beta1ExternalMetrics(
                                        backend = '0', 
                                        namespace = '0', 
                                        query = '0', 
                                        server_address = '0', ), 
                                    target = kserve.models.v1beta1_metric_target.V1beta1MetricTarget(
                                        average_utilization = 56, 
                                        average_value = None, 
                                        type = '0', 
                                        value = None, ), ), 
                                podmetric = kserve.models.v1beta1_pod_metric_source.V1beta1PodMetricSource(
                                    metric = kserve.models.v1beta1_pod_metrics.V1beta1PodMetrics(
                                        backend = '0', 
                                        metric_names = [
                                            '0'
                                            ], 
                                        operation_over_time = '0', 
                                        query = '0', 
                                        server_address = '0', ), 
                                    target = kserve.models.v1beta1_metric_target.V1beta1MetricTarget(
                                        average_utilization = 56, 
                                        average_value = None, 
                                        type = '0', 
                                        value = None, ), ), 
                                resource = kserve.models.v1beta1_resource_metric_source.V1beta1ResourceMetricSource(
                                    name = '0', 
                                    target = kserve.models.v1beta1_metric_target.V1beta1MetricTarget(
                                        average_utilization = 56, 
                                        average_value = None, 
                                        type = '0', 
                                        value = None, ), ), 
                                type = '0', )
                            ], ), 
                    automount_service_account_token = True, 
                    batcher = kserve.models.v1beta1_batcher.V1beta1Batcher(
                        max_batch_size = 56, 
                        max_latency = 56, 
                        timeout = 56, ), 
                    canary_traffic_percent = 56, 
                    container_concurrency = 56, 
                    containers = [
                        None
                        ], 
                    deployment_strategy = None, 
                    dns_config = None, 
                    dns_policy = '0', 
                    enable_service_links = True, 
                    ephemeral_containers = [
                        None
                        ], 
                    host_aliases = [
                        None
                        ], 
                    host_ipc = True, 
                    host_network = True, 
                    host_pid = True, 
                    host_users = True, 
                    hostname = '0', 
                    hostname_override = '0', 
                    huggingface = kserve.models.v1beta1_hugging_face_runtime_spec.V1beta1HuggingFaceRuntimeSpec(
                        args = [
                            '0'
                            ], 
                        command = [
                            '0'
                            ], 
                        env = [
                            None
                            ], 
                        env_from = [
                            None
                            ], 
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        ports = [
                            None
                            ], 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resize_policy = [
                            None
                            ], 
                        resources = None, 
                        restart_policy = '0', 
                        restart_policy_rules = [
                            None
                            ], 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage = kserve.models.v1beta1_model_storage_spec.V1beta1ModelStorageSpec(
                            key = '0', 
                            parameters = {
                                'key' : '0'
                                }, 
                            path = '0', 
                            schema_path = '0', ), 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        volume_devices = [
                            None
                            ], 
                        volume_mounts = [
                            None
                            ], 
                        working_dir = '0', ), 
                    image_pull_secrets = [
                        None
                        ], 
                    init_containers = [
                        None
                        ], 
                    labels = {
                        'key' : '0'
                        }, 
                    lightgbm = kserve.models.v1beta1_light_gbm_spec.V1beta1LightGBMSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    logger = kserve.models.v1beta1_logger_spec.V1beta1LoggerSpec(
                        batch_interval = '0', 
                        batch_size = 56, 
                        marshaller_url = '0', 
                        metadata_annotations = [
                            '0'
                            ], 
                        metadata_headers = [
                            '0'
                            ], 
                        mode = '0', 
                        url = '0', ), 
                    max_replicas = 56, 
                    min_replicas = 56, 
                    model = kserve.models.v1beta1_model_spec.V1beta1ModelSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        model_format = kserve.models.v1beta1_model_format.V1beta1ModelFormat(
                            name = '0', 
                            version = '0', ), 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    name = '0', 
                    node_name = '0', 
                    node_selector = {
                        'key' : '0'
                        }, 
                    onnx = kserve.models.v1beta1_onnx_runtime_spec.V1beta1ONNXRuntimeSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    os = None, 
                    overhead = {
                        'key' : None
                        }, 
                    paddle = kserve.models.v1beta1_paddle_server_spec.V1beta1PaddleServerSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    pmml = kserve.models.v1beta1_pmml_spec.V1beta1PMMLSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    preemption_policy = '0', 
                    priority = 56, 
                    priority_class_name = '0', 
                    pytorch = kserve.models.v1beta1_torch_serve_spec.V1beta1TorchServeSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    readiness_gates = [
                        None
                        ], 
                    resource_claims = [
                        None
                        ], 
                    resources = None, 
                    restart_policy = '0', 
                    runtime_class_name = '0', 
                    scale_metric = '0', 
                    scale_metric_type = '0', 
                    scale_target = 56, 
                    scheduler_name = '0', 
                    scheduling_gates = [
                        None
                        ], 
                    security_context = None, 
                    service_account = '0', 
                    service_account_name = '0', 
                    set_hostname_as_fqdn = True, 
                    share_process_namespace = True, 
                    sklearn = kserve.models.v1beta1_sk_learn_spec.V1beta1SKLearnSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    storage_container_name = '0', 
                    storage_uris = [
                        kserve.models.v1beta1_storage_uri.V1beta1StorageUri(
                            mount_path = '0', 
                            uri = '0', )
                        ], 
                    subdomain = '0', 
                    tensorflow = kserve.models.v1beta1_tf_serving_spec.V1beta1TFServingSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    termination_grace_period_seconds = 56, 
                    timeout = 56, 
                    tolerations = [
                        None
                        ], 
                    topology_spread_constraints = [
                        None
                        ], 
                    triton = kserve.models.v1beta1_triton_spec.V1beta1TritonSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    volumes = [
                        None
                        ], 
                    worker_spec = kserve.models.v1beta1_worker_spec.V1beta1WorkerSpec(
                        active_deadline_seconds = 56, 
                        affinity = None, 
                        automount_service_account_token = True, 
                        dns_config = None, 
                        dns_policy = '0', 
                        enable_service_links = True, 
                        host_ipc = True, 
                        host_network = True, 
                        host_pid = True, 
                        host_users = True, 
                        hostname = '0', 
                        hostname_override = '0', 
                        node_name = '0', 
                        os = None, 
                        pipeline_parallel_size = 56, 
                        preemption_policy = '0', 
                        priority = 56, 
                        priority_class_name = '0', 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_class_name = '0', 
                        scheduler_name = '0', 
                        security_context = None, 
                        service_account = '0', 
                        service_account_name = '0', 
                        set_hostname_as_fqdn = True, 
                        share_process_namespace = True, 
                        subdomain = '0', 
                        tensor_parallel_size = 56, 
                        termination_grace_period_seconds = 56, ), 
                    xgboost = kserve.models.v1beta1_xg_boost_spec.V1beta1XGBoostSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), ), 
                traffic_percent = 56
            )
        else :
            return V1beta1CanarySpec(
                predictor = kserve.models.v1beta1_predictor_spec.V1beta1PredictorSpec(
                    active_deadline_seconds = 56, 
                    affinity = None, 
                    annotations = {
                        'key' : '0'
                        }, 
                    auto_scaling = kserve.models.v1beta1_auto_scaling_spec.V1beta1AutoScalingSpec(
                        behavior = None, 
                        metrics = [
                            kserve.models.v1beta1_metrics_spec.V1beta1MetricsSpec(
                                external = kserve.models.v1beta1_external_metric_source.V1beta1ExternalMetricSource(
                                    authentication_ref = kserve.models.v1beta1_ext_metric_authentication.V1beta1ExtMetricAuthentication(
                                        auth_modes = '0', 
                                        authentication_ref = kserve.models.v1beta1_authentication_ref.V1beta1AuthenticationRef(
                                            name = '0', ), ), 
                                    metric = kserve.models.v1beta1_external_metrics.V1beta1ExternalMetrics(
                                        backend = '0', 
                                        namespace = '0', 
                                        query = '0', 
                                        server_address = '0', ), 
                                    target = kserve.models.v1beta1_metric_target.V1beta1MetricTarget(
                                        average_utilization = 56, 
                                        average_value = None, 
                                        type = '0', 
                                        value = None, ), ), 
                                podmetric = kserve.models.v1beta1_pod_metric_source.V1beta1PodMetricSource(
                                    metric = kserve.models.v1beta1_pod_metrics.V1beta1PodMetrics(
                                        backend = '0', 
                                        metric_names = [
                                            '0'
                                            ], 
                                        operation_over_time = '0', 
                                        query = '0', 
                                        server_address = '0', ), 
                                    target = kserve.models.v1beta1_metric_target.V1beta1MetricTarget(
                                        average_utilization = 56, 
                                        average_value = None, 
                                        type = '0', 
                                        value = None, ), ), 
                                resource = kserve.models.v1beta1_resource_metric_source.V1beta1ResourceMetricSource(
                                    name = '0', 
                                    target = kserve.models.v1beta1_metric_target.V1beta1MetricTarget(
                                        average_utilization = 56, 
                                        average_value = None, 
                                        type = '0', 
                                        value = None, ), ), 
                                type = '0', )
                            ], ), 
                    automount_service_account_token = True, 
                    batcher = kserve.models.v1beta1_batcher.V1beta1Batcher(
                        max_batch_size = 56, 
                        max_latency = 56, 
                        timeout = 56, ), 
                    canary_traffic_percent = 56, 
                    container_concurrency = 56, 
                    containers = [
                        None
                        ], 
                    deployment_strategy = None, 
                    dns_config = None, 
                    dns_policy = '0', 
                    enable_service_links = True, 
                    ephemeral_containers = [
                        None
                        ], 
                    host_aliases = [
                        None
                        ], 
                    host_ipc = True, 
                    host_network = True, 
                    host_pid = True, 
                    host_users = True, 
                    hostname = '0', 
                    hostname_override = '0', 
                    huggingface = kserve.models.v1beta1_hugging_face_runtime_spec.V1beta1HuggingFaceRuntimeSpec(
                        args = [
                            '0'
                            ], 
                        command = [
                            '0'
                            ], 
                        env = [
                            None
                            ], 
                        env_from = [
                            None
                            ], 
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        ports = [
                            None
                            ], 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resize_policy = [
                            None
                            ], 
                        resources = None, 
                        restart_policy = '0', 
                        restart_policy_rules = [
                            None
                            ], 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage = kserve.models.v1beta1_model_storage_spec.V1beta1ModelStorageSpec(
                            key = '0', 
                            parameters = {
                                'key' : '0'
                                }, 
                            path = '0', 
                            schema_path = '0', ), 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        volume_devices = [
                            None
                            ], 
                        volume_mounts = [
                            None
                            ], 
                        working_dir = '0', ), 
                    image_pull_secrets = [
                        None
                        ], 
                    init_containers = [
                        None
                        ], 
                    labels = {
                        'key' : '0'
                        }, 
                    lightgbm = kserve.models.v1beta1_light_gbm_spec.V1beta1LightGBMSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    logger = kserve.models.v1beta1_logger_spec.V1beta1LoggerSpec(
                        batch_interval = '0', 
                        batch_size = 56, 
                        marshaller_url = '0', 
                        metadata_annotations = [
                            '0'
                            ], 
                        metadata_headers = [
                            '0'
                            ], 
                        mode = '0', 
                        url = '0', ), 
                    max_replicas = 56, 
                    min_replicas = 56, 
                    model = kserve.models.v1beta1_model_spec.V1beta1ModelSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        model_format = kserve.models.v1beta1_model_format.V1beta1ModelFormat(
                            name = '0', 
                            version = '0', ), 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    name = '0', 
                    node_name = '0', 
                    node_selector = {
                        'key' : '0'
                        }, 
                    onnx = kserve.models.v1beta1_onnx_runtime_spec.V1beta1ONNXRuntimeSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    os = None, 
                    overhead = {
                        'key' : None
                        }, 
                    paddle = kserve.models.v1beta1_paddle_server_spec.V1beta1PaddleServerSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    pmml = kserve.models.v1beta1_pmml_spec.V1beta1PMMLSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    preemption_policy = '0', 
                    priority = 56, 
                    priority_class_name = '0', 
                    pytorch = kserve.models.v1beta1_torch_serve_spec.V1beta1TorchServeSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    readiness_gates = [
                        None
                        ], 
                    resource_claims = [
                        None
                        ], 
                    resources = None, 
                    restart_policy = '0', 
                    runtime_class_name = '0', 
                    scale_metric = '0', 
                    scale_metric_type = '0', 
                    scale_target = 56, 
                    scheduler_name = '0', 
                    scheduling_gates = [
                        None
                        ], 
                    security_context = None, 
                    service_account = '0', 
                    service_account_name = '0', 
                    set_hostname_as_fqdn = True, 
                    share_process_namespace = True, 
                    sklearn = kserve.models.v1beta1_sk_learn_spec.V1beta1SKLearnSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    storage_container_name = '0', 
                    storage_uris = [
                        kserve.models.v1beta1_storage_uri.V1beta1StorageUri(
                            mount_path = '0', 
                            uri = '0', )
                        ], 
                    subdomain = '0', 
                    tensorflow = kserve.models.v1beta1_tf_serving_spec.V1beta1TFServingSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    termination_grace_period_seconds = 56, 
                    timeout = 56, 
                    tolerations = [
                        None
                        ], 
                    topology_spread_constraints = [
                        None
                        ], 
                    triton = kserve.models.v1beta1_triton_spec.V1beta1TritonSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), 
                    volumes = [
                        None
                        ], 
                    worker_spec = kserve.models.v1beta1_worker_spec.V1beta1WorkerSpec(
                        active_deadline_seconds = 56, 
                        affinity = None, 
                        automount_service_account_token = True, 
                        dns_config = None, 
                        dns_policy = '0', 
                        enable_service_links = True, 
                        host_ipc = True, 
                        host_network = True, 
                        host_pid = True, 
                        host_users = True, 
                        hostname = '0', 
                        hostname_override = '0', 
                        node_name = '0', 
                        os = None, 
                        pipeline_parallel_size = 56, 
                        preemption_policy = '0', 
                        priority = 56, 
                        priority_class_name = '0', 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_class_name = '0', 
                        scheduler_name = '0', 
                        security_context = None, 
                        service_account = '0', 
                        service_account_name = '0', 
                        set_hostname_as_fqdn = True, 
                        share_process_namespace = True, 
                        subdomain = '0', 
                        tensor_parallel_size = 56, 
                        termination_grace_period_seconds = 56, ), 
                    xgboost = kserve.models.v1beta1_xg_boost_spec.V1beta1XGBoostSpec(
                        image = '0', 
                        image_pull_policy = '0', 
                        lifecycle = None, 
                        liveness_probe = None, 
                        name = '0', 
                        protocol_version = '0', 
                        readiness_probe = None, 
                        resources = None, 
                        restart_policy = '0', 
                        runtime_version = '0', 
                        security_context = None, 
                        startup_probe = None, 
                        stdin = True, 
                        stdin_once = True, 
                        storage_uri = '0', 
                        termination_message_path = '0', 
                        termination_message_policy = '0', 
                        tty = True, 
                        working_dir = '0', ), ),
                traffic_percent = 56,
        )

    def testV1beta1CanarySpec(self):
        """Test V1beta1CanarySpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
