/*
Copyright 2023 The KServe Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kserve/kserve/pkg/apis/serving/v1alpha1"
	scheme "github.com/kserve/kserve/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterLocalModelsGetter has a method to return a ClusterLocalModelInterface.
// A group's client should implement this interface.
type ClusterLocalModelsGetter interface {
	ClusterLocalModels(namespace string) ClusterLocalModelInterface
}

// ClusterLocalModelInterface has methods to work with ClusterLocalModel resources.
type ClusterLocalModelInterface interface {
	Create(ctx context.Context, clusterLocalModel *v1alpha1.ClusterLocalModel, opts v1.CreateOptions) (*v1alpha1.ClusterLocalModel, error)
	Update(ctx context.Context, clusterLocalModel *v1alpha1.ClusterLocalModel, opts v1.UpdateOptions) (*v1alpha1.ClusterLocalModel, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterLocalModel *v1alpha1.ClusterLocalModel, opts v1.UpdateOptions) (*v1alpha1.ClusterLocalModel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterLocalModel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterLocalModelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterLocalModel, err error)
	ClusterLocalModelExpansion
}

// clusterLocalModels implements ClusterLocalModelInterface
type clusterLocalModels struct {
	*gentype.ClientWithList[*v1alpha1.ClusterLocalModel, *v1alpha1.ClusterLocalModelList]
}

// newClusterLocalModels returns a ClusterLocalModels
func newClusterLocalModels(c *ServingV1alpha1Client, namespace string) *clusterLocalModels {
	return &clusterLocalModels{
		gentype.NewClientWithList[*v1alpha1.ClusterLocalModel, *v1alpha1.ClusterLocalModelList](
			"clusterlocalmodels",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.ClusterLocalModel { return &v1alpha1.ClusterLocalModel{} },
			func() *v1alpha1.ClusterLocalModelList { return &v1alpha1.ClusterLocalModelList{} }),
	}
}
