apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: llama31-8b-draft-target
  annotations:
    serving.kserve.io/secretName: hf-secret
spec:
  model:
    uri: hf://meta-llama/Llama-3.1-8B-Instruct
    name: meta-llama/Llama-3.1-8B-Instruct
  speculator:
    model:
      uri: hf://meta-llama/Llama-3.2-1B-Instruct
    config:
      method: draft_model
      num_speculative_tokens: "5"
      max_model_len: "8192"
      draft_tensor_parallel_size: "1"
  replicas: 4
  router:
    scheduler: {}
    route: {}
    gateway: {}
  template:
    containers:
      - name: main
        env:
          - name: VLLM_USE_V1
            value: "1"
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
