apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: qwen3-next-80b-mtp
  annotations:
    serving.kserve.io/secretName: hf-secret
spec:
  model:
    uri: hf://RedHatAI/Qwen3-Next-80B-A3B-FP8
    name: RedHatAI/Qwen3-Next-80B-A3B-FP8
  speculator:
    config:
      method: qwen3_next_mtp
      num_speculative_tokens: "1"
  replicas: 2
  parallelism:
    tensor: 4
  router:
    scheduler: {}
    route: {}
    gateway: {}
  template:
    containers:
      - name: main
        env:
          - name: VLLM_USE_V1
            value: "1"
        resources:
          limits:
            nvidia.com/gpu: "4"
          requests:
            nvidia.com/gpu: "4"
