apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-tracing
spec:
  tracing:
    serviceName: inference-server
    otelExporterEndpoint: "http://otel-collector:4317"
    tracesSampler: "parentbased_traceidratio"
    tracesSamplerArg: "0.05"
    tracesExporter: "otlp"
