apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-tracing
spec:
  tracing:
    exporterEndpoint: "http://otel-collector:4317"
    sampler: "parentbased_traceidratio"
    samplerArg: "0.05"
    exporter: "otlp"
