# coding: utf-8

# flake8: noqa
"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from kfserving.models.knative_condition import KnativeCondition
from kfserving.models.knative_volatile_time import KnativeVolatileTime
from kfserving.models.v1alpha2_alibi_explain_spec import V1alpha2AlibiExplainSpec
from kfserving.models.v1alpha2_custom_spec import V1alpha2CustomSpec
from kfserving.models.v1alpha2_explain_spec import V1alpha2ExplainSpec
from kfserving.models.v1alpha2_framework_config import V1alpha2FrameworkConfig
from kfserving.models.v1alpha2_frameworks_config import V1alpha2FrameworksConfig
from kfserving.models.v1alpha2_kf_service import V1alpha2KFService
from kfserving.models.v1alpha2_kf_service_list import V1alpha2KFServiceList
from kfserving.models.v1alpha2_kf_service_spec import V1alpha2KFServiceSpec
from kfserving.models.v1alpha2_kf_service_status import V1alpha2KFServiceStatus
from kfserving.models.v1alpha2_model_spec import V1alpha2ModelSpec
from kfserving.models.v1alpha2_py_torch_spec import V1alpha2PyTorchSpec
from kfserving.models.v1alpha2_sk_learn_spec import V1alpha2SKLearnSpec
from kfserving.models.v1alpha2_status_configuration_spec import V1alpha2StatusConfigurationSpec
from kfserving.models.v1alpha2_tensor_rt_spec import V1alpha2TensorRTSpec
from kfserving.models.v1alpha2_tensorflow_spec import V1alpha2TensorflowSpec
from kfserving.models.v1alpha2_xg_boost_spec import V1alpha2XGBoostSpec
