apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    serving.kserve.io/server-type: vllmserver
  name: kserve-vllmserver
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8080"
    serving.kserve.io/kernelcache-supported: "true"
  containers:
  - args:
    - --port=8080
    - --served-model-name={{.Name}}
    - --model=/mnt/models
    command:
    - python3
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: LMCACHE_USE_EXPERIMENTAL
      value: "True"
    - name: HF_HOME
      value: /tmp/hf
    - name: VLLM_CONFIG_ROOT
      value: /tmp
    - name: VLLM_WORKER_MULTIPROC_METHOD
      value: spawn
    - name: VLLM_CACHE_ROOT
      value: /tmp/vllm
    - name: HOME
      value: /tmp
    image: vllm/vllm-openai:v0.28.0
    name: kserve-container
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v1/models
        port: 8080
        protocol: TCP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
    startupProbe:
      failureThreshold: 60
      httpGet:
        path: /v1/models
        port: 8080
        protocol: TCP
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 10
    volumeMounts:
    - mountPath: /dev/shm
      name: devshm
  hostIPC: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
    priority: 1
    version: "1"
  volumes:
  - emptyDir:
      medium: Memory
    name: devshm
