from _typeshed import Incomplete

GRPC_GENERATED_VERSION: str
GRPC_VERSION: Incomplete
EXPECTED_ERROR_RELEASE: str
SCHEDULED_RELEASE_DATE: str

class GRPCInferenceServiceStub:
    ServerLive: Incomplete
    ServerReady: Incomplete
    ModelReady: Incomplete
    ServerMetadata: Incomplete
    ModelMetadata: Incomplete
    ModelInfer: Incomplete
    RepositoryModelLoad: Incomplete
    RepositoryModelUnload: Incomplete
    def __init__(self, channel) -> None: ...

class GRPCInferenceServiceServicer:
    def ServerLive(self, request, context) -> None: ...
    def ServerReady(self, request, context) -> None: ...
    def ModelReady(self, request, context) -> None: ...
    def ServerMetadata(self, request, context) -> None: ...
    def ModelMetadata(self, request, context) -> None: ...
    def ModelInfer(self, request, context) -> None: ...
    def RepositoryModelLoad(self, request, context) -> None: ...
    def RepositoryModelUnload(self, request, context) -> None: ...

def add_GRPCInferenceServiceServicer_to_server(servicer, server) -> None: ...

class GRPCInferenceService:
    @staticmethod
    def ServerLive(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
    @staticmethod
    def ServerReady(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
    @staticmethod
    def ModelReady(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
    @staticmethod
    def ServerMetadata(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
    @staticmethod
    def ModelMetadata(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
    @staticmethod
    def ModelInfer(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
    @staticmethod
    def RepositoryModelLoad(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
    @staticmethod
    def RepositoryModelUnload(request, target, options=..., channel_credentials: Incomplete | None = ..., call_credentials: Incomplete | None = ..., insecure: bool = ..., compression: Incomplete | None = ..., wait_for_ready: Incomplete | None = ..., timeout: Incomplete | None = ..., metadata: Incomplete | None = ...): ...
