# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1alpha1ModelCacheNodeGroupSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'node_selector': 'dict(str, str)',
        'storage_limit': 'ResourceQuantity'
    }

    attribute_map = {
        'node_selector': 'nodeSelector',
        'storage_limit': 'storageLimit'
    }

    def __init__(self, node_selector=None, storage_limit=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1ModelCacheNodeGroupSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._node_selector = None
        self._storage_limit = None
        self.discriminator = None

        self.node_selector = node_selector
        self.storage_limit = storage_limit

    @property
    def node_selector(self):
        """Gets the node_selector of this V1alpha1ModelCacheNodeGroupSpec.  # noqa: E501


        :return: The node_selector of this V1alpha1ModelCacheNodeGroupSpec.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._node_selector

    @node_selector.setter
    def node_selector(self, node_selector):
        """Sets the node_selector of this V1alpha1ModelCacheNodeGroupSpec.


        :param node_selector: The node_selector of this V1alpha1ModelCacheNodeGroupSpec.  # noqa: E501
        :type: dict(str, str)
        """
        if self.local_vars_configuration.client_side_validation and node_selector is None:  # noqa: E501
            raise ValueError("Invalid value for `node_selector`, must not be `None`")  # noqa: E501

        self._node_selector = node_selector

    @property
    def storage_limit(self):
        """Gets the storage_limit of this V1alpha1ModelCacheNodeGroupSpec.  # noqa: E501


        :return: The storage_limit of this V1alpha1ModelCacheNodeGroupSpec.  # noqa: E501
        :rtype: ResourceQuantity
        """
        return self._storage_limit

    @storage_limit.setter
    def storage_limit(self, storage_limit):
        """Sets the storage_limit of this V1alpha1ModelCacheNodeGroupSpec.


        :param storage_limit: The storage_limit of this V1alpha1ModelCacheNodeGroupSpec.  # noqa: E501
        :type: ResourceQuantity
        """
        if self.local_vars_configuration.client_side_validation and storage_limit is None:  # noqa: E501
            raise ValueError("Invalid value for `storage_limit`, must not be `None`")  # noqa: E501

        self._storage_limit = storage_limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ModelCacheNodeGroupSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1ModelCacheNodeGroupSpec):
            return True

        return self.to_dict() != other.to_dict()
