# Copyright 2019 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1alpha1KernelCacheIdentity(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'factors': 'dict(str, str)',
        'footprints': 'V1alpha1KernelCacheFootprints'
    }

    attribute_map = {
        'factors': 'factors',
        'footprints': 'footprints'
    }

    def __init__(self, factors=None, footprints=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1KernelCacheIdentity - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._factors = None
        self._footprints = None
        self.discriminator = None

        if factors is not None:
            self.factors = factors
        self.footprints = footprints

    @property
    def factors(self):
        """Gets the factors of this V1alpha1KernelCacheIdentity.  # noqa: E501

        Factors contains the normalized values used to calculate the footprints.  # noqa: E501

        :return: The factors of this V1alpha1KernelCacheIdentity.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._factors

    @factors.setter
    def factors(self, factors):
        """Sets the factors of this V1alpha1KernelCacheIdentity.

        Factors contains the normalized values used to calculate the footprints.  # noqa: E501

        :param factors: The factors of this V1alpha1KernelCacheIdentity.  # noqa: E501
        :type: dict(str, str)
        """

        self._factors = factors

    @property
    def footprints(self):
        """Gets the footprints of this V1alpha1KernelCacheIdentity.  # noqa: E501


        :return: The footprints of this V1alpha1KernelCacheIdentity.  # noqa: E501
        :rtype: V1alpha1KernelCacheFootprints
        """
        return self._footprints

    @footprints.setter
    def footprints(self, footprints):
        """Sets the footprints of this V1alpha1KernelCacheIdentity.


        :param footprints: The footprints of this V1alpha1KernelCacheIdentity.  # noqa: E501
        :type: V1alpha1KernelCacheFootprints
        """
        if self.local_vars_configuration.client_side_validation and footprints is None:  # noqa: E501
            raise ValueError("Invalid value for `footprints`, must not be `None`")  # noqa: E501

        self._footprints = footprints

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1KernelCacheIdentity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1KernelCacheIdentity):
            return True

        return self.to_dict() != other.to_dict()
