# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1beta1AutoscalerConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "scale_down_stabilization_window_seconds": "str",
        "scale_up_stabilization_window_seconds": "str",
    }

    attribute_map = {
        "scale_down_stabilization_window_seconds": "scaleDownStabilizationWindowSeconds",
        "scale_up_stabilization_window_seconds": "scaleUpStabilizationWindowSeconds",
    }

    def __init__(
        self,
        scale_down_stabilization_window_seconds=None,
        scale_up_stabilization_window_seconds=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """V1beta1AutoscalerConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._scale_down_stabilization_window_seconds = None
        self._scale_up_stabilization_window_seconds = None
        self.discriminator = None

        if scale_down_stabilization_window_seconds is not None:
            self.scale_down_stabilization_window_seconds = (
                scale_down_stabilization_window_seconds
            )
        if scale_up_stabilization_window_seconds is not None:
            self.scale_up_stabilization_window_seconds = (
                scale_up_stabilization_window_seconds
            )

    @property
    def scale_down_stabilization_window_seconds(self):
        """Gets the scale_down_stabilization_window_seconds of this V1beta1AutoscalerConfig.  # noqa: E501


        :return: The scale_down_stabilization_window_seconds of this V1beta1AutoscalerConfig.  # noqa: E501
        :rtype: str
        """
        return self._scale_down_stabilization_window_seconds

    @scale_down_stabilization_window_seconds.setter
    def scale_down_stabilization_window_seconds(
        self, scale_down_stabilization_window_seconds
    ):
        """Sets the scale_down_stabilization_window_seconds of this V1beta1AutoscalerConfig.


        :param scale_down_stabilization_window_seconds: The scale_down_stabilization_window_seconds of this V1beta1AutoscalerConfig.  # noqa: E501
        :type: str
        """

        self._scale_down_stabilization_window_seconds = (
            scale_down_stabilization_window_seconds
        )

    @property
    def scale_up_stabilization_window_seconds(self):
        """Gets the scale_up_stabilization_window_seconds of this V1beta1AutoscalerConfig.  # noqa: E501


        :return: The scale_up_stabilization_window_seconds of this V1beta1AutoscalerConfig.  # noqa: E501
        :rtype: str
        """
        return self._scale_up_stabilization_window_seconds

    @scale_up_stabilization_window_seconds.setter
    def scale_up_stabilization_window_seconds(
        self, scale_up_stabilization_window_seconds
    ):
        """Sets the scale_up_stabilization_window_seconds of this V1beta1AutoscalerConfig.


        :param scale_up_stabilization_window_seconds: The scale_up_stabilization_window_seconds of this V1beta1AutoscalerConfig.  # noqa: E501
        :type: str
        """

        self._scale_up_stabilization_window_seconds = (
            scale_up_stabilization_window_seconds
        )

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1AutoscalerConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1beta1AutoscalerConfig):
            return True

        return self.to_dict() != other.to_dict()
