# Single parameter: set namespace for all resources
namespace: kserve-lab

resources:
  - hf-token-secret.yaml
  - service_account.yaml
  - model-pvc.yaml
  - model_weights_job.yaml
  - llmisvc_config_default.yaml
  - llmisvc_config_prefix_cache.yaml
  # Include one of the two below (same resource name)
  - inference_default.yaml
  # - inference_prefix_cache.yaml
  - service_monitor.yaml
  - gateway.yaml
  - ai-gateway-route.yaml
