---
apiVersion: batch/v1
kind: Job
metadata:
  name: gpt-oss-20b-init-job
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: gpt-oss-20b-pvc
            readOnly: false
      containers:
        - image: kserve/kserve-storage-initializer:v0.17.0
          name: storage-initializer
          args:
            - hf://RedHatAI/gpt-oss-20b
            - /mnt/models
          env:
            - name: HF_HOME
              value: /tmp/hf
            - name: HF_XET_NUM_CONCURRENT_RANGE_GETS
              value: "8"
            - name: HF_XET_HIGH_PERFORMANCE
              value: "True"
            - name: HF_HUB_DISABLE_TELEMETRY
              value: "1"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: HF_TOKEN
          resources:
            requests:
              cpu: "2"
              memory: "16Gi"
            limits:
              cpu: "8"
              memory: "32Gi"
          volumeMounts:
            - name: pvc
              mountPath: "/mnt/models"
              readOnly: false
