{{- $selfSignedCfg := include "llm-isvc-resources.selfSignedCertsConfig" . | fromJson -}}
{{- if $selfSignedCfg.enabled }}
{{- $certs := include "llm-isvc-resources.webhookCertData" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: llmisvc-webhook-server-cert
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $certs.CACert | b64enc }}
  tls.crt: {{ $certs.Cert | b64enc }}
  tls.key: {{ $certs.Key | b64enc }}
{{- end }}
