name: Upload Python Package

on:
  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-kserve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"

      - name: Install UV
        run: ./test/scripts/gh-actions/setup-uv.sh
      - name: KServe - Build and publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          cd python/kserve
          uv build
          uv publish
  publish-storage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"

      - name: Install UV
        run: ./test/scripts/gh-actions/setup-uv.sh

      - name: KServe Storage - Build and publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.KSERVE_STORAGE_PYPI_TOKEN }}
        run: |
          cd python/storage
          uv build
          uv publish
